/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agroindustria_definitivo;

import java.awt.Component;
import static java.awt.image.ImageObserver.WIDTH;
import java.beans.PropertyVetoException;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import static java.lang.Thread.sleep;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author aluno
 */
public class Tela_Cadastro extends javax.swing.JFrame {

    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    public Tela_Cadastro(String usuario) {
        initComponents();
       //this.setExtendedState(MAXIMIZED_BOTH);
        jPanel1.getMaximumSize();
        tema();
        relogio();
        con=ConeBD.ConexaoBD.ConectarBD();
    }

    public void relogio() {
        new Thread() {
            public void run() {
                while (0 == 0) {
                    SimpleDateFormat hora = new SimpleDateFormat("HH:mm:ss");
                    SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
                    //jLabel3.setText(hora.format(new Date()));
                    //jLabel4.setText(data.format(new Date()));
                    try {
                        sleep(10000);
                    } catch (Exception e) {

                    }
                }
            }
        }.start();
    }

    public void tema() {
        try {
            try {
                UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Tela_Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception e) {

        }
    }
    
    public String preco_venda_eventos() {
        try {
            String sql2 = "select sum(preco_total) as preco_total from preco_venda_evento";            
            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getString("preco_total");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro de Consulta");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de Preco Venda"+ex.getMessage());
        }
        return null;
    }
    public String preco_venda_ru() {
        try {
            String sql2 = "select sum(preco_total) as preco_total from preco_venda_ru";            
            pst = con.prepareStatement(sql2);
            rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getString("preco_total");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro de Consulta");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de Preco Venda"+ex.getMessage());
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DesktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        produtos = new javax.swing.JLabel();
        pordutoru = new javax.swing.JLabel();
        produtoseventos = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        movvendas = new javax.swing.JLabel();
        movru = new javax.swing.JLabel();
        moveventos = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        backup = new javax.swing.JLabel();
        restore = new javax.swing.JLabel();
        jToolBar4 = new javax.swing.JToolBar();
        relatoriovenda = new javax.swing.JLabel();
        relatorioproduto = new javax.swing.JLabel();
        relatoriousuario = new javax.swing.JLabel();
        relatorioevento = new javax.swing.JLabel();
        relatorioru = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setBackground(new java.awt.Color(64, 105, 255));
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(40000, 40000));

        DesktopPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DesktopPane.setPreferredSize(new java.awt.Dimension(1440, 1500));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1436, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        jToolBar1.setForeground(new java.awt.Color(240, 240, 240));
        jToolBar1.setRollover(true);

        produtos.setForeground(new java.awt.Color(240, 240, 240));
        produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/salvar.png"))); // NOI18N
        produtos.setText("k");
        produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosMouseClicked(evt);
            }
        });
        jToolBar1.add(produtos);

        pordutoru.setForeground(new java.awt.Color(240, 240, 240));
        pordutoru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/package.png"))); // NOI18N
        pordutoru.setText("k");
        pordutoru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pordutoruMouseClicked(evt);
            }
        });
        jToolBar1.add(pordutoru);

        produtoseventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/icons8-manual-do-usuário-24.png"))); // NOI18N
        produtoseventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoseventosMouseClicked(evt);
            }
        });
        jToolBar1.add(produtoseventos);

        jToolBar2.setForeground(new java.awt.Color(240, 240, 240));
        jToolBar2.setRollover(true);

        movvendas.setForeground(new java.awt.Color(240, 240, 240));
        movvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/basket_add.png"))); // NOI18N
        movvendas.setText("k");
        movvendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movvendasMouseClicked(evt);
            }
        });
        jToolBar2.add(movvendas);

        movru.setForeground(new java.awt.Color(240, 240, 240));
        movru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/package.png"))); // NOI18N
        movru.setText("k");
        movru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movruMouseClicked(evt);
            }
        });
        jToolBar2.add(movru);

        moveventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/flag_red.png"))); // NOI18N
        moveventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveventosMouseClicked(evt);
            }
        });
        jToolBar2.add(moveventos);

        jToolBar3.setForeground(new java.awt.Color(240, 240, 240));
        jToolBar3.setRollover(true);

        backup.setForeground(new java.awt.Color(240, 240, 240));
        backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/database_add.png"))); // NOI18N
        backup.setText("k");
        backup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backupMouseClicked(evt);
            }
        });
        jToolBar3.add(backup);

        restore.setForeground(new java.awt.Color(240, 240, 240));
        restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/database_delete.png"))); // NOI18N
        restore.setText("k");
        restore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restoreMouseClicked(evt);
            }
        });
        jToolBar3.add(restore);

        jToolBar4.setForeground(new java.awt.Color(240, 240, 240));
        jToolBar4.setRollover(true);

        relatoriovenda.setForeground(new java.awt.Color(240, 240, 240));
        relatoriovenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report_add.png"))); // NOI18N
        relatoriovenda.setText("k");
        relatoriovenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatoriovendaMouseClicked(evt);
            }
        });
        jToolBar4.add(relatoriovenda);

        relatorioproduto.setForeground(new java.awt.Color(240, 240, 240));
        relatorioproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report_disk.png"))); // NOI18N
        relatorioproduto.setText("k");
        relatorioproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatorioprodutoMouseClicked(evt);
            }
        });
        jToolBar4.add(relatorioproduto);

        relatoriousuario.setForeground(new java.awt.Color(240, 240, 240));
        relatoriousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report_user.png"))); // NOI18N
        relatoriousuario.setText("k");
        relatoriousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatoriousuarioMouseClicked(evt);
            }
        });
        jToolBar4.add(relatoriousuario);

        relatorioevento.setForeground(new java.awt.Color(240, 240, 240));
        relatorioevento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report.png"))); // NOI18N
        relatorioevento.setText("k");
        relatorioevento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatorioeventoMouseClicked(evt);
            }
        });
        jToolBar4.add(relatorioevento);

        relatorioru.setForeground(new java.awt.Color(240, 240, 240));
        relatorioru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report_picture.png"))); // NOI18N
        relatorioru.setText("k");
        relatorioru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relatorioruMouseClicked(evt);
            }
        });
        jToolBar4.add(relatorioru);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Cadastrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/salvar.png"))); // NOI18N
        jMenuItem1.setText("Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/package.png"))); // NOI18N
        jMenuItem3.setText("Produtos RU");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/icons8-manual-do-usuário-24.png"))); // NOI18N
        jMenuItem12.setText("Produtos Eventos");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/user.png"))); // NOI18N
        jMenuItem2.setText("Usuários");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Movimentações");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/basket_add.png"))); // NOI18N
        jMenuItem6.setText("Vendas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/package.png"))); // NOI18N
        jMenuItem7.setText("R.U");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/flag_red.png"))); // NOI18N
        jMenuItem9.setText("Eventos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Ferramentas");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/database_add.png"))); // NOI18N
        jMenuItem10.setText("Backup");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/database_delete.png"))); // NOI18N
        jMenuItem11.setText("Restore");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Relatórios");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report_add.png"))); // NOI18N
        jMenuItem8.setText("Relatório de Vendas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report_disk.png"))); // NOI18N
        jMenuItem4.setText("Relatório Produtos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report.png"))); // NOI18N
        jMenuItem13.setText("Relatório de Eventos ");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_bernan/report_picture.png"))); // NOI18N
        jMenuItem14.setText("Relatório enviados R.U");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Nova_Tela_Produtos produtos = new Nova_Tela_Produtos();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Nova_Tela_Usuarios produtos = new Nova_Tela_Usuarios();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        final List<String> codigos = new ArrayList<String>();
        JFileChooser chooser = new JFileChooser();
        int sav = chooser.showSaveDialog(null);
        if (sav == JFileChooser.APPROVE_OPTION) {
            File arq = chooser.getSelectedFile().getAbsoluteFile();
            String dir = arq.getPath();

            codigos.add("C:\\Program Files\\PostgreSQL\\11\\bin\\pg_dump.exe");

            codigos.add("-h");
            codigos.add("localhost");
            codigos.add("-p");
            codigos.add("5432");
            codigos.add("-U");
            codigos.add("postgres");
            codigos.add("-F");
            codigos.add("c");
            codigos.add("-b");
            codigos.add("-v");
            codigos.add("-f");
            codigos.add(dir + ".backup");
            codigos.add("agroindustria");

            ProcessBuilder pb = new ProcessBuilder(codigos);

            pb.environment().put("PGPASSWORD", "123");

            try {
                final Process process = pb.start();

                try (BufferedReader r = new BufferedReader(
                        new InputStreamReader(process.getErrorStream()))) {
                    String line = r.readLine();
                    while (line != null) {
                        System.err.println(line);
                        line = r.readLine();
                    }
                }

                process.waitFor();
                process.destroy();
                JOptionPane.showMessageDialog(null, "O Backup foi um sucesso.");

            } catch (IOException | InterruptedException e) {

                JOptionPane.showMessageDialog(null, "O Backup falhou" + e.getMessage());

            }
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        JFileChooser open = new JFileChooser();
        int op = open.showOpenDialog(null);
        if (op == JFileChooser.APPROVE_OPTION) {
            File arq = open.getSelectedFile().getAbsoluteFile();
            String pathDoArquivo = arq.toString(); //aqui pega o caminho do backup
            //aqui você testa se a string recebeu o caminho do arquivo
            final List<String> codigo = new ArrayList<>();

            codigo.add("C:\\Program Files\\PostgreSQL\\11\\bin\\pg_restore.exe");
            codigo.add("-h");
            codigo.add("localhost");
            codigo.add("-p");
            codigo.add("5432");
            codigo.add("-U");
            codigo.add("postgres");
            codigo.add("-c");
            codigo.add("-d");
            codigo.add("agroindustria");
            codigo.add("-v");
            codigo.add(pathDoArquivo);

            ProcessBuilder pb = new ProcessBuilder(codigo);

            pb.environment().put("PGPASSWORD", "123");

            try {
                final Process process = pb.start();
                final BufferedReader r = new BufferedReader(
                        new InputStreamReader(process.getErrorStream()));
                String line = r.readLine();
                while (line != null) {
                    System.err.println(line);
                    line = r.readLine();

                }
                r.close();

                process.waitFor();
                process.destroy();

                JOptionPane.showMessageDialog(null, "Restauração foi um sucesso!");

            } catch (IOException | InterruptedException e) {

                JOptionPane.showMessageDialog(null, "Erro de restauração " + e.getMessage());

            }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        Nova_Tela_Venda produtos = new Nova_Tela_Venda();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Nova_Tela_Relatorio produtos = new Nova_Tela_Relatorio();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       String sql = "select * from produtos";        
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            JRResultSetDataSource relat = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport("src\\Relatorio\\Produtos_3.jasper", null, relat);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (SQLException | JRException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Erro de Emissão de Relatórios Botao Imprimir: " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Nova_Tela_Venda produtos = new Nova_Tela_Venda();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Tela_RU produtos = new Tela_RU();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Tela_Eventos eventos = new Tela_Eventos();
        DesktopPane.add(eventos);
        eventos.setVisible(true);
        eventos.setPosicao();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Nova_Tela_Produtos_RU produtos = new Nova_Tela_Produtos_RU();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Nova_Tela_Produtos_Eventos produtos = new Nova_Tela_Produtos_Eventos();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Nova_Tela_Relatorio_Eventos relatorio = new Nova_Tela_Relatorio_Eventos();
        DesktopPane.add(relatorio);
        relatorio.setVisible(true);
        relatorio.setPosicao();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        Nova_Tela_Relatorio_RU relatorio_ru = new Nova_Tela_Relatorio_RU();
        DesktopPane.add(relatorio_ru);
        relatorio_ru.setVisible(true);
        relatorio_ru.setPosicao();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosMouseClicked
        Nova_Tela_Produtos produtos = new Nova_Tela_Produtos();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_produtosMouseClicked

    private void pordutoruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pordutoruMouseClicked
        Nova_Tela_Produtos_RU produtos = new Nova_Tela_Produtos_RU();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();

    }//GEN-LAST:event_pordutoruMouseClicked

    private void produtoseventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoseventosMouseClicked
        Nova_Tela_Produtos_Eventos produtos = new Nova_Tela_Produtos_Eventos();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_produtoseventosMouseClicked

    private void movvendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movvendasMouseClicked
        Nova_Tela_Venda produtos = new Nova_Tela_Venda();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_movvendasMouseClicked

    private void movruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movruMouseClicked
        Tela_RU produtos = new Tela_RU();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();
    }//GEN-LAST:event_movruMouseClicked

    private void moveventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveventosMouseClicked
        Tela_Eventos eventos = new Tela_Eventos();
        DesktopPane.add(eventos);
        eventos.setVisible(true);
        eventos.setPosicao();
    }//GEN-LAST:event_moveventosMouseClicked

    private void backupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupMouseClicked
                // TODO add your handling code here:
        final List<String> codigos = new ArrayList<String>();
        JFileChooser chooser = new JFileChooser();
        int sav = chooser.showSaveDialog(null);
        if (sav == JFileChooser.APPROVE_OPTION) {
            File arq = chooser.getSelectedFile().getAbsoluteFile();
            String dir = arq.getPath();

            codigos.add("C:\\Program Files\\PostgreSQL\\10\\bin\\pg_dump.exe");

            codigos.add("-h");
            codigos.add("localhost");
            codigos.add("-p");
            codigos.add("5432");
            codigos.add("-U");
            codigos.add("postgres");
            codigos.add("-F");
            codigos.add("c");
            codigos.add("-b");
            codigos.add("-v");
            codigos.add("-f");
            codigos.add(dir + ".backup");
            codigos.add("agroindustria");

            ProcessBuilder pb = new ProcessBuilder(codigos);

            pb.environment().put("PGPASSWORD", "123");

            try {
                final Process process = pb.start();

                try (BufferedReader r = new BufferedReader(
                        new InputStreamReader(process.getErrorStream()))) {
                    String line = r.readLine();
                    while (line != null) {
                        System.err.println(line);
                        line = r.readLine();
                    }
                }

                process.waitFor();
                process.destroy();
                JOptionPane.showMessageDialog(null, "O Backup foi um sucesso.");

            } catch (IOException | InterruptedException e) {

                JOptionPane.showMessageDialog(null, "O Backup falhou" + e.getMessage());

            }
        }
    }//GEN-LAST:event_backupMouseClicked

    private void restoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restoreMouseClicked
        JFileChooser open = new JFileChooser();
        int op = open.showOpenDialog(null);
        if (op == JFileChooser.APPROVE_OPTION) {
            File arq = open.getSelectedFile().getAbsoluteFile();
            String pathDoArquivo = arq.toString(); //aqui pega o caminho do backup
            //aqui você testa se a string recebeu o caminho do arquivo
            final List<String> codigo = new ArrayList<>();

            codigo.add("C:\\Program Files\\PostgreSQL\\10\\bin\\pg_restore.exe");
            codigo.add("-h");
            codigo.add("localhost");
            codigo.add("-p");
            codigo.add("5432");
            codigo.add("-U");
            codigo.add("postgres");
            codigo.add("-c");
            codigo.add("-d");
            codigo.add("agroindustria");
            codigo.add("-v");
            codigo.add(pathDoArquivo);

            ProcessBuilder pb = new ProcessBuilder(codigo);

            pb.environment().put("PGPASSWORD", "123");

            try {
                final Process process = pb.start();
                final BufferedReader r = new BufferedReader(
                        new InputStreamReader(process.getErrorStream()));
                String line = r.readLine();
                while (line != null) {
                    System.err.println(line);
                    line = r.readLine();

                }
                r.close();

                process.waitFor();
                process.destroy();

                JOptionPane.showMessageDialog(null, "Restauração foi um sucesso!");

            } catch (IOException | InterruptedException e) {

                JOptionPane.showMessageDialog(null, "Erro de restauração " + e.getMessage());

            }
        }
    }//GEN-LAST:event_restoreMouseClicked

    private void relatoriovendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatoriovendaMouseClicked
        Nova_Tela_Relatorio produtos = new Nova_Tela_Relatorio();
        DesktopPane.add(produtos);
        produtos.setVisible(true);
        produtos.setPosicao();        
    }//GEN-LAST:event_relatoriovendaMouseClicked

    private void relatorioprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorioprodutoMouseClicked
        String sql = "select * from produtos";        
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            JRResultSetDataSource relat = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport("src\\Relatorio\\Produtos_3.jasper", null, relat);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (SQLException | JRException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Erro de Emissão de Relatórios Botao Imprimir: " + ex.getMessage());
        }
    }//GEN-LAST:event_relatorioprodutoMouseClicked

    private void relatoriousuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatoriousuarioMouseClicked
                String sql = "select * from usuarios";        
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            JRResultSetDataSource relat = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport("src\\Relatorio\\Usuarios_3.jasper", null, relat);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.toFront();
        } catch (SQLException | JRException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Erro de Emissão de Relatórios Botao Imprimir: " + ex.getMessage());
        }
    }//GEN-LAST:event_relatoriousuarioMouseClicked

    private void relatorioeventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorioeventoMouseClicked
        Nova_Tela_Relatorio_Eventos relatorio = new Nova_Tela_Relatorio_Eventos();
        DesktopPane.add(relatorio);
        relatorio.setVisible(true);
        relatorio.setPosicao();
    }//GEN-LAST:event_relatorioeventoMouseClicked

    private void relatorioruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relatorioruMouseClicked
        Nova_Tela_Relatorio_RU relatorio = new Nova_Tela_Relatorio_RU();
        DesktopPane.add(relatorio);
        relatorio.setVisible(true);
        relatorio.setPosicao();
    }//GEN-LAST:event_relatorioruMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel backup;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JLabel moveventos;
    private javax.swing.JLabel movru;
    private javax.swing.JLabel movvendas;
    private javax.swing.JLabel pordutoru;
    private javax.swing.JLabel produtos;
    private javax.swing.JLabel produtoseventos;
    private javax.swing.JLabel relatorioevento;
    private javax.swing.JLabel relatorioproduto;
    private javax.swing.JLabel relatorioru;
    private javax.swing.JLabel relatoriousuario;
    private javax.swing.JLabel relatoriovenda;
    private javax.swing.JLabel restore;
    // End of variables declaration//GEN-END:variables
}
